//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIVE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class givedbEntities : DbContext
    {
        public givedbEntities()
            : base("name=givedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KidBalance> KidBalances { get; set; }
        public DbSet<KidsData> KidsDatas { get; set; }
        public DbSet<KidTransaction> KidTransactions { get; set; }
        public DbSet<SubWallet> SubWallets { get; set; }
        public DbSet<CharityGroup> CharityGroups { get; set; }
        public DbSet<LoginType> LoginTypes { get; set; }
    }
}
