//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIVE
{
    using System;
    using System.Collections.Generic;
    
    public partial class KidBalance
    {
        public int Id { get; set; }
        public Nullable<int> KidId { get; set; }
        public Nullable<long> Balance { get; set; }
        public Nullable<int> Freedom { get; set; }
        public Nullable<int> Savings { get; set; }
        public Nullable<int> Give { get; set; }
        public Nullable<int> Play { get; set; }
        public Nullable<int> Education { get; set; }
    
        public virtual SubWallet SubWallet { get; set; }
    }
}
