//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIVE
{
    using System;
    using System.Collections.Generic;
    
    public partial class KidTransaction
    {
        public int Id { get; set; }
        public Nullable<int> FromKidID { get; set; }
        public string ToAddress { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> SubWalletType { get; set; }
        public string ReceivedDescription { get; set; }
    
        public virtual SubWallet SubWallet { get; set; }
    }
}
