//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIVE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubWallet
    {
        public SubWallet()
        {
            this.KidBalances = new HashSet<KidBalance>();
            this.KidTransactions = new HashSet<KidTransaction>();
        }
    
        public int Id { get; set; }
        public string SubWalletType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<KidBalance> KidBalances { get; set; }
        public virtual ICollection<KidTransaction> KidTransactions { get; set; }
    }
}
